branch-defaults:
  dev:
    environment: node-express-env
    group_suffix: null
global:
  application_name: AtextaWeb
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm start"